### ISSUE TITLE
Баг интерфейса в приложении

### ISSUE THREAD

**Issue by sl1ther** [nareshalka/nareshalka#1]
Когда в приложении нахожу ответы, последний вопрос никогда не видно полностью. На скрине видно, что последний вопрос я не вижу полностью и пролистнуть ниже не могу. Это не единичный случай, так всё время происходит. В качестве решения проблемы могу предложить просто добавить пустое место ниже последнего вопроса.
![Screenshot_2022-02-07-11-28-51](https://user-images.githubusercontent.com/99175163/152761559-dd0b79d3-f16b-4224-be46-9b74145fc0ca.png)

**Comment by nareshalka** [comment]
Исправлено в версии 3.2.3. Просьба обновиться на последнюю версию.
